title: Librería del Goblin 
description: Documentación mal hecha y vulgar

theme: jekyll-theme-hacker

paginate: 20
plugins:
- jekyll-paginate

disqus: estasleyendoesto

show_downloads: false

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
  extensions: fenced_code_blocks
