title: Goblin 
description: Para la documentación mal hecha

theme: jekyll-theme-hacker

paginate: 10
plugins:
- jekyll-paginate

disqus: estasleyendoesto

show_downloads: true

github:
  otra_url: www.manga.com
